# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cworker.proto"a\n\x10InferenceRequest\x12-\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1f.InferenceRequest.InferenceData\x1a\x1e\n\rInferenceData\x12\r\n\x05image\x18\x01 \x01(\t"0\n\x0eInferenceReply\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\r\x12\x0c\n\x04pred\x18\x02 \x01(\r2;\n\x06Worker\x12\x31\n\tinference\x12\x11.InferenceRequest\x1a\x0f.InferenceReply"\x00\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "worker_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _INFERENCEREQUEST._serialized_start = 16
    _INFERENCEREQUEST._serialized_end = 113
    _INFERENCEREQUEST_INFERENCEDATA._serialized_start = 83
    _INFERENCEREQUEST_INFERENCEDATA._serialized_end = 113
    _INFERENCEREPLY._serialized_start = 115
    _INFERENCEREPLY._serialized_end = 163
    _WORKER._serialized_start = 165
    _WORKER._serialized_end = 224
# @@protoc_insertion_point(module_scope)
